project_id = "vzyrzhfxdrtgyhpddvlj"

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-account-locked]
verify_jwt = false

[functions.send-walkup-welcome]
verify_jwt = false

[functions.send-password-updated]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
