project_id = "vzyrzhfxdrtgyhpddvlj"

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-account-locked]
verify_jwt = false

[functions.send-walkup-welcome]
verify_jwt = false

[functions.send-password-updated]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.calendly-availability]
verify_jwt = false

[functions.calendly-book]
verify_jwt = false

[functions.calendly-cancel]
verify_jwt = false

[functions.cal-availability]
verify_jwt = true

[functions.cal-book]
verify_jwt = true

[functions.cal-cancel]
verify_jwt = true
