project_id = "hqcdsjznvyywmoylmjur"

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-account-locked]
verify_jwt = false

[functions.send-walkup-welcome]
verify_jwt = false

[functions.send-password-updated]
verify_jwt = false
